version: '3'
services:
  app-java:
    image: ${ACR_NAME}.azurecr.io/skillmap-api:v1 # O Azure vai substituir isso
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq-service
      # As outras variáveis virão do "Application Settings" do Azure
    depends_on:
      - rabbitmq-service

  rabbitmq-service:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"